"""initial schema

Revision ID: 1003dafc7073
Revises: 
Create Date: 2026-05-12 21:38:57.305375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1003dafc7073'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_tone_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('mean_tone', sa.Float(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'score_date', name='uq_country_tone_date')
    )
    with op.batch_alter_table('country_tone_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_tone_scores_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_tone_scores_score_date'), ['score_date'], unique=False)

    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('to_dkk', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'rate_date', name='uq_fx_currency_date')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_fx_rates_rate_date'), ['rate_date'], unique=False)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('country_code', sa.String(length=4), nullable=True),
    sa.Column('pluto_tier', sa.String(length=20), nullable=False),
    sa.Column('is_benchmark', sa.Boolean(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('fundamentals_updated_at', sa.DateTime(), nullable=True),
    sa.Column('wsb_aliases', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_ticker'), ['ticker'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('cash_balance_dkk', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=40), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_observed_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_user_id'), ['user_id'], unique=False)

    op.create_table('daily_score_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('price_at_snapshot_dkk', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'snapshot_date', name='uq_score_stock_date')
    )
    with op.batch_alter_table('daily_score_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_score_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_score_snapshots_stock_id'), ['stock_id'], unique=False)

    op.create_table('insider_activity_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('net_share_change', sa.Float(), nullable=False),
    sa.Column('net_value_usd', sa.Float(), nullable=False),
    sa.Column('txn_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'score_date', name='uq_insider_stock_date')
    )
    with op.batch_alter_table('insider_activity_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insider_activity_scores_score_date'), ['score_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_activity_scores_stock_id'), ['stock_id'], unique=False)

    op.create_table('model_portfolio_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('pick_strategy', sa.String(length=40), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('entry_price_dkk', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'pick_strategy', 'stock_id', name='uq_pick_date_strategy_stock')
    )
    with op.batch_alter_table('model_portfolio_picks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_portfolio_picks_pick_strategy'), ['pick_strategy'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_portfolio_picks_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_portfolio_picks_stock_id'), ['stock_id'], unique=False)

    op.create_table('news_headlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=800), nullable=False),
    sa.Column('compound_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'link', name='uq_news_headline_link')
    )
    with op.batch_alter_table('news_headlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_headlines_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_headlines_stock_id'), ['stock_id'], unique=False)

    op.create_table('news_sentiment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('mean_compound', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('top_headline', sa.String(length=400), nullable=True),
    sa.Column('top_headline_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'score_date', name='uq_news_stock_date')
    )
    with op.batch_alter_table('news_sentiment_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_sentiment_scores_score_date'), ['score_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_sentiment_scores_stock_id'), ['stock_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost_dkk', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_id', name='uq_position_user_stock')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_user_id'), ['user_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('close_dkk', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_price_stock_date')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_trade_date'), ['trade_date'], unique=False)

    op.create_table('reddit_mention_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('mention_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('subreddits_seen', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'mention_date', name='uq_reddit_stock_date')
    )
    with op.batch_alter_table('reddit_mention_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reddit_mention_counts_mention_date'), ['mention_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reddit_mention_counts_stock_id'), ['stock_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price_dkk', sa.Float(), nullable=False),
    sa.Column('fee_dkk', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_id', name='uq_watchlist_user_stock')
    )
    with op.batch_alter_table('watchlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_entries_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_entries_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('watchlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_entries_stock_id'))

    op.drop_table('watchlist_entries')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_trades_stock_id'))

    op.drop_table('trades')
    with op.batch_alter_table('reddit_mention_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reddit_mention_counts_stock_id'))
        batch_op.drop_index(batch_op.f('ix_reddit_mention_counts_mention_date'))

    op.drop_table('reddit_mention_counts')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_trade_date'))
        batch_op.drop_index(batch_op.f('ix_price_history_stock_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_user_id'))
        batch_op.drop_index(batch_op.f('ix_positions_stock_id'))

    op.drop_table('positions')
    with op.batch_alter_table('news_sentiment_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_sentiment_scores_stock_id'))
        batch_op.drop_index(batch_op.f('ix_news_sentiment_scores_score_date'))

    op.drop_table('news_sentiment_scores')
    with op.batch_alter_table('news_headlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_headlines_stock_id'))
        batch_op.drop_index(batch_op.f('ix_news_headlines_published_at'))

    op.drop_table('news_headlines')
    with op.batch_alter_table('model_portfolio_picks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_portfolio_picks_stock_id'))
        batch_op.drop_index(batch_op.f('ix_model_portfolio_picks_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_model_portfolio_picks_pick_strategy'))

    op.drop_table('model_portfolio_picks')
    with op.batch_alter_table('insider_activity_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insider_activity_scores_stock_id'))
        batch_op.drop_index(batch_op.f('ix_insider_activity_scores_score_date'))

    op.drop_table('insider_activity_scores')
    with op.batch_alter_table('daily_score_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_score_snapshots_stock_id'))
        batch_op.drop_index(batch_op.f('ix_daily_score_snapshots_snapshot_date'))

    op.drop_table('daily_score_snapshots')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_stock_id'))

    op.drop_table('alert_rules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_ticker'))

    op.drop_table('stocks')
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_rate_date'))
        batch_op.drop_index(batch_op.f('ix_fx_rates_currency'))

    op.drop_table('fx_rates')
    with op.batch_alter_table('country_tone_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_tone_scores_score_date'))
        batch_op.drop_index(batch_op.f('ix_country_tone_scores_country_code'))

    op.drop_table('country_tone_scores')
    # ### end Alembic commands ###
